### ISSUE TITLE
Broken in labeled statements

### ISSUE THREAD

**Issue by Jarred-Sumner** [zigtools/zls#1073]
### Zig Version

0.11.0-dev.1934+10c74631b

### Zig Language Server Version

HEAD

### Steps to Reproduce

No completions or types appear for declarations defined in labeled statements
 
```zig
const Ref = struct {
    a: u32 = 0,
};

pub fn function() void {
    hey: while (true) {
        var ref = Ref{};
        r
        // does not display "ref" in the autocomplete list
    }
}

pub fn main() anyerror!void {
    function();
}
```

<img width="586" alt="image" src="https://user-images.githubusercontent.com/709451/225822872-144113b4-0488-450d-9db2-3022212ee243.png">

### Expected Behavior

Completions should work as before

They still work if outside a scope like so:

<img width="519" alt="image" src="https://user-images.githubusercontent.com/709451/225822619-afdd7d12-451b-493b-80d0-f361ae5d334c.png">

They also work if there is no label for the scope:

<img width="585" alt="image" src="https://user-images.githubusercontent.com/709451/225822751-7be171d6-4015-4626-91e2-3178baf2720a.png">

### Actual Behavior

Completions do not work in labeled statements

Reverting to 973d33d435890062e056b1901ce4e0adf958e36a works around it

**Comment by SuperAuguste** [comment]
Same kind of bug as the thing I fixed in 4126e209d262deff24d1eec51880001e2f164f9d; I'll try and fix this now.

**Comment by SuperAuguste** [comment]
With https://github.com/zigtools/zls/pull/1074

![image](https://user-images.githubusercontent.com/19855629/225826867-adf1fbca-806d-46de-8817-63c0d2c90dac.png)

Can you confirm this fixes the issue for you locally? Thanks! :)

**Comment by Jarred-Sumner** [comment]
@SuperAuguste  doesn't fix it

<img width="584" alt="image" src="https://user-images.githubusercontent.com/709451/225827226-8d6ac38a-9fe8-47bc-89a6-130b6d7037f1.png">

098a8453e21fa4023c61a824c03b464a1d77c0d0

**Comment by SuperAuguste** [comment]
Ah my bad, forgot to handle all the other cases with labels (only fixed simple blocks). I'll get that going now. :)

**Comment by SuperAuguste** [comment]
Could you pull rebase the PR and try again? Tested locally with all the labelled cases I could think of and this should be all good now :)

**Comment by Jarred-Sumner** [comment]
works

thank you!

**Comment by Jarred-Sumner** [comment]
This seems to be happening again in the latest version of zls

Note how `this` is defined as a function argument and it does not appear in the list of completions.

<img width="759" alt="image" src="https://user-images.githubusercontent.com/709451/229758260-26288ca9-6639-4610-8dfd-6ec1427e1487.png">
