### ISSUE TITLE
non-deterministic zls_gen

### ISSUE THREAD

**Issue by bmwiedemann** [zigtools/zls#2138]
### Zig Version

0.13.0

### ZLS Version

0.13.0

### Steps to Reproduce and Observed Behavior

build zls twice (from scratch)

Builds embed a random path from
```diff
- /home/abuild/rpmbuild/BUILD/zls-0.13.0/zig-cache/o/1c703156d1c748dd822850009e362839/zls_gen --generate-version-data 0.13.0 --langref_path /usr/share/doc/packages/zig/langref.html --generate-version-data-path /home/abuild/rpmbuild/BUILD/zls-0.13.0/zig-cache/o/e9fa9483a7e7709690e1a2c451e3f26d/version_data_0.13.0.zig
+ /home/abuild/rpmbuild/BUILD/zls-0.13.0/zig-cache/o/a584116cfed34531fa759dd6d5a6e146/zls_gen --generate-version-data 0.13.0 --langref_path /usr/share/doc/packages/zig/langref.html --generate-version-data-path /home/abuild/rpmbuild/BUILD/zls-0.13.0/zig-cache/o/3467172f659a38bcf17b0fa61da120b0/version_data_0.13.0.zig
```

### Expected Behavior

Builds should produce two bit-identical binaries

**Comment by Techatrix** [comment]
This has already been fixed by #2000. Also note that Zig does not guarantee reproducible debug builds.

**Comment by bmwiedemann** [comment]
Via https://github.com/ziglang/zig/issues/22663 I found that this is probably not fixed by #2000 but this patch helped:

```diff
--- a/build.zig
+++ b/build.zig
@@ -88,7 +88,9 @@ pub fn build(b: *Build) !void {
     const gen_exe = b.addExecutable(.{
         .name = "zls_gen",
         .root_source_file = b.path("src/config_gen/config_gen.zig"),
-        .target = b.host,
+        .target = b.resolveTargetQuery(.{
+            .cpu_model = .baseline,
+        }),
         .single_threaded = true,
     });
```

zig might get a toolchain patch to make results reproducible without.
