### ISSUE TITLE
Autofix breaks for escaped identifiers with names matching keywords

### ISSUE THREAD

**Issue by kavika13** [zigtools/zls#2453]
### Zig Version

0.15.0-dev.1552

### ZLS Version

0.15.0-dev.368

### Client / Code Editor / Extensions

vscode with ziglang plugin

### Steps to Reproduce and Observed Behavior

1. enable autofix settings
2. add `const @"struct" = "test";` variable
3. save the file
4. add a line farther down `std.debug.print("{s}\n", .{@"struct"});`
5. save the file

after step 3 it doesn't add an autofix at all

if your variable is a capture variable name (from a `switch { .val => |@"struct"| {} }` or `if(nullable) |@"struct"|`), then zls will add a nonsensical autofix:
`_ = ; //autofix`
...and in such cases the autofix doesn't get removed if you reference the variable and save the file

### Expected Behavior

after step 3, it should add the line `_ = @"struct";  // autofix`
after step 5, it should remove that line

### Log Output

```shell
2025-08-20 03:34:03.413 [info] Starting ZLS      0.15.0-dev.368+e114d7e6 @ 'C:\dev\zls\zig-out\bin\zls.exe'
2025-08-20 03:34:03.413 [info] Log File:         C:\Users\myusername\AppData\Local\Temp\zls\zls.log (debug)
2025-08-20 03:34:03.413 [info] Client Info:      Visual Studio Code (1.103.1)
2025-08-20 03:34:03.413 [info] added Workspace Folder: file:///c%3A/test/autofix-test
2025-08-20 03:34:03.449 [info] Set config option 'semantic_tokens' to "partial"
2025-08-20 03:34:03.449 [info] Set config option 'warn_style' to true
2025-08-20 03:34:03.449 [info] Set config option 'builtin_path' to "C:\\Users\\myusername\\AppData\\Local\\Temp\\zls\\builtin.zig"
2025-08-20 03:34:03.451 [info] Set config option 'zig_lib_path' to "C:\\Users\\myusername\\AppData\\Roaming\\Code\\User\\globalStorage\\ziglang.vscode-zig\\zig\\x86_64-windows-0.15.0-dev.1585+ee85c8b6d\\lib"
2025-08-20 03:34:03.451 [info] Set config option 'zig_exe_path' to "c:\\Users\\myusername\\AppData\\Roaming\\Code\\User\\globalStorage\\ziglang.vscode-zig\\zig\\x86_64-windows-0.15.0-dev.1585+ee85c8b6d\\zig.exe"
2025-08-20 03:34:03.451 [info] Set config option 'build_runner_path' to "C:\\Users\\myusername\\AppData\\Local\\Temp\\zls\\build_runner\\cf46548b062a7e79e448e80c05616097\\build_runner.zig"
2025-08-20 03:34:03.452 [info] Set config option 'global_cache_path' to "C:\\Users\\myusername\\AppData\\Local\\Temp\\zls"
2025-08-20 03:34:03.452 [info] trying to start Build-On-Save for 'file:///c%3A/test/autofix-test'
```

**Comment by kavika13** [comment]
I think this may have gotten fixed in 1840a4b81be10e900b1ab0343178638452dc28aa

**Comment by techatrix** [comment]
This case still fails:
```zig
test {
    var @"struct" = {};
}
```

Test case for [tests/lsp_features/code_actions.zig](https://github.com/zigtools/zls/blob/master/tests/lsp_features/code_actions.zig):
```zig
test "discard value with escaped identifier" {
    try testAutofix(
        \\test {
        \\    var @"struct" = {};
        \\    const bar, var @"union" = .{ 1, 2 };
        \\}
        \\
    ,
        \\test {
        \\    var @"struct" = {};
        \\    _ = @"struct"; // autofix
        \\    const bar, var @"union" = .{ 1, 2 };
        \\    _ = @"union"; // autofix
        \\    _ = bar; // autofix
        \\}
        \\
    );
}
```

```
====== expected this output: =========
test {
    var @"struct" = {};
    _ = @"struct"; // autofix
    const bar, var @"union" = .{ 1, 2 };
    _ = @"union"; // autofix
    _ = bar; // autofix
}
␃

======== instead found this: =========
test {
    var @"struct" = {};
    const bar, var @"union" = .{ 1, 2 };
    _ = bar; // autofix
}
␃
```

**Comment by llogick** [comment]
Discrepancy between how identifiers are stored (stripped) and looked up -- specifically, DocumentScope's pushDeclaration() always strips `@"` and `"`.

```diff
diff --git a/src/features/code_actions.zig b/src/features/code_actions.zig
index 11f999d7..6d7e2f02 100644
--- a/src/features/code_actions.zig
+++ b/src/features/code_actions.zig
@@ -397,7 +397,7 @@ fn handleUnusedVariableOrConstant(builder: *Builder, loc: offsets.Loc) !void {
 
     if (!builder.wantKind(.@"source.fixAll") and !builder.wantKind(.quickfix)) return;
 
-    const identifier_name = offsets.locToSlice(builder.handle.tree.source, loc);
+    const identifier_name = offsets.identifierIndexToSlice(builder.handle.tree.source, loc.start, .name);
 
     const tree = builder.handle.tree;
 
@@ -418,7 +418,7 @@ fn handleUnusedVariableOrConstant(builder: *Builder, loc: offsets.Loc) !void {
     if (insert_token >= tree.tokens.len) return;
     if (tree.tokenTag(insert_token) != .semicolon) return;
 
-    const insert_index, const new_text = try createDiscardText(builder, identifier_name, insert_token, false, false);
+    const insert_index, const new_text = try createDiscardText(builder, offsets.identifierIndexToSlice(builder.handle.tree.source, loc.start, .full), insert_token, false, false);
 
     if (builder.wantKind(.@"source.fixAll")) {
         try builder.fixall_text_edits.append(builder.arena, builder.createTextEditPos(insert_index, new_text));
```
