### ISSUE TITLE
Can't build on windows with latest Zig master

### ISSUE THREAD

**Issue by genejo** [zigtools/zls#483]
I'm trying to call `zig build -Drelease-safe`. Zig is latest master (2022-05-02), but it fails. Does anyone know what I may be missing?

```
c:\bin\zls>zig version
0.10.0-dev.2033+3679d737f
```

```zig
c:\bin\zls>zig build -Drelease-safe
C:\bin\zls\src\main.zig:1457:48: error: expected error union type, found 'std.child_process.ChildProcess'
        var process = try std.ChildProcess.init(&[_][]const u8{ zig_exe_path, "fmt", "--stdin" }, allocator);
                                               ^
zls...The following command exited with error code 1:
C:\bin\zig-windows-x86_64\zig.exe build-exe C:\bin\zls\src\main.zig -OReleaseSafe --cache-dir C:\bin\zls\zig-cache --global-cache-dir C:\Users\eugen\AppData\Local\zig --name zls --pkg-begin build_options C:\bin\zls\zig-cache\options\H9AR0LKhRsNLPCkAU3kSn-zvYq8-9gC59lDnXgE_CH0psH885s1rdv7SSsAB5aNT --pkg-end --pkg-begin known-folders C:\bin\zls\src\known-folders\known-folders.zig --pkg-end --pkg-begin zinput C:\bin\zls\src\zinput\src\main.zig --pkg-end --enable-cache
error: the following build command failed with exit code 1:
c:\bin\zls\zig-cache\o\402843ed16b3807462781bae6796feb9\build.exe C:\bin\zig-windows-x86_64\zig.exe c:\bin\zls c:\bin\zls\zig-cache C:\Users\eugen\AppData\Local\zig -Drelease-safe
```

Also tried with `-Ddata_version=master`.

**Comment by nektro** [comment]
fixed with #481

**Comment by tpeacock19** [comment]
I'm still unable to build this on arch linux. It shows the same error as the github actions here: https://github.com/zigtools/zls/actions/runs/2297826191

**Comment by jesselucas** [comment]
Same error on debian 11
`./src/main.zig:1457:48: error: expected error union type, found 'std.child_process.ChildProcess'`

**Comment by nektro** [comment]
yeah that pull is still open, this issue shouldnt be closed
